version: "2.1"

services:
    desktop:
        image: michaelbatz/desktop-env
        build: .
        ports:
        - "3389:3389"
        environment:
            ROOT_PASSWORD: "root"
            USER_USERNAME: "desktop"
            USER_PASSWORD: "dektop"
        volumes:
        - home:/home

volumes:
    home:
