version: "2.1"

services:
    desktop:
        image: michaelbatz/desktop-env
        build: .
        privileged: true
        ports:
        - "2222:22"
        environment:
            ROOT_PASSWORD: "root"
            USER_USERNAME: "desktop"
            USER_PASSWORD: "desktop"
        volumes:
        - home:/home

volumes:
    home:
